// This file is auto-generated by scripts/generate_file_index.js
// Do not edit manually if you plan to re-run the script.
// CLEARED: Using only Cloud Files (Firestore) as per user request.
const FILE_INDEX = {
    // Legacy files are removed. Use Firestore for file management.
};
